#ifdef EVENT_ENUMS
	#define DECLARE_EVENT( ev ) ev
#endif

#ifdef EVENT_STRINGS
	#define DECLARE_EVENT( ev ) #ev
#endif

// BFP - Highly modified to match original BFP demo networking events
DECLARE_EVENT( EV_NONE ),					// 0

DECLARE_EVENT( EV_UNUSED_INDEX1 ),			// 1
DECLARE_EVENT( EV_UNUSED_INDEX2 ),			// 2
DECLARE_EVENT( EV_UNUSED_INDEX3 ),			// 3
DECLARE_EVENT( EV_UNUSED_INDEX4 ),			// 4
DECLARE_EVENT( EV_UNUSED_INDEX5 ),			// 5
DECLARE_EVENT( EV_UNUSED_INDEX6 ),			// 6
DECLARE_EVENT( EV_UNUSED_INDEX7 ),			// 7
DECLARE_EVENT( EV_UNUSED_INDEX8 ),			// 8
DECLARE_EVENT( EV_UNUSED_INDEX9 ),			// 9

DECLARE_EVENT( EV_MELEE_READY ),			// BFP - EV_MELEE_READY (10), original BFP: preparing melee
DECLARE_EVENT( EV_MELEE ),					// BFP - EV_MELEE (11), melee attack
DECLARE_EVENT( EV_UNUSED_INDEX12 ),			// 12
DECLARE_EVENT( EV_TIER_RESET ),				// EV_TIER_RESET (13), reset tier when the player respawns and changes to the default or a bit less ki energy?
// BFP - EV_TIER_0-4 (14-18), when the player frags, increases their PL and obtains a new skill (in the last tier, transforms)
DECLARE_EVENT( EV_TIER_0 ),					// 14
DECLARE_EVENT( EV_TIER_1 ),					// 15
DECLARE_EVENT( EV_TIER_2 ),					// 16
DECLARE_EVENT( EV_TIER_3 ),					// 17
DECLARE_EVENT( EV_TIER_4 ),					// 18

DECLARE_EVENT( EV_ZANZOKEN_IN ),			// BFP - EV_ZANZOKEN_IN (19), Short-Range Teleport (Zanzoken)
DECLARE_EVENT( EV_ZANZOKEN_OUT ),			// BFP - EV_ZANZOKEN_OUT (20), stop/leaves zanzoken
DECLARE_EVENT( EV_KI_BOOST ),				// BFP - EV_KI_BOOST (21), original BFP: enables aura and ki trail
DECLARE_EVENT( EV_ENABLE_FLIGHT ),			// BFP - EV_ENABLE_FLIGHT (22), enable flight
DECLARE_EVENT( EV_FOOTSTEP ),				// 23
DECLARE_EVENT( EV_FOOTSTEP_METAL ),			// 24
DECLARE_EVENT( EV_FOOTSPLASH ),				// 25
DECLARE_EVENT( EV_FOOTWADE ),				// 26
DECLARE_EVENT( EV_SWIM ),					// 27
DECLARE_EVENT( EV_STEP_4 ),					// 28
DECLARE_EVENT( EV_STEP_8 ),					// 29
DECLARE_EVENT( EV_STEP_12 ),				// 30
DECLARE_EVENT( EV_STEP_16 ),				// 31

DECLARE_EVENT( EV_FALL_SHORT ),				// 32
DECLARE_EVENT( EV_FALL_MEDIUM ),			// 33
DECLARE_EVENT( EV_FALL_FAR ),				// 34
DECLARE_EVENT( EV_JUMP_PAD ),				// boing sound at origin, jump sound on player
DECLARE_EVENT( EV_JUMP ),					// 36
DECLARE_EVENT( EV_JUMP_2 ),					// 37

DECLARE_EVENT( EV_WATER_TOUCH ),			// foot touches
DECLARE_EVENT( EV_WATER_LEAVE ),			// foot leaves
DECLARE_EVENT( EV_WATER_UNDER ),			// head touches
DECLARE_EVENT( EV_WATER_CLEAR ),			// head leaves
DECLARE_EVENT( EV_ITEM_PICKUP ),			// normal item pickups are predictable
DECLARE_EVENT( EV_GLOBAL_ITEM_PICKUP ),		// powerup / team sounds are broadcast to everyone
DECLARE_EVENT( EV_NOAMMO ),					// 44
DECLARE_EVENT( EV_CHANGE_WEAPON ),			// 45
DECLARE_EVENT( EV_FIRE_WEAPON ),			// 46

DECLARE_EVENT( EV_USE_ITEM0 ),				// 47
DECLARE_EVENT( EV_USE_ITEM1 ),				// 48
DECLARE_EVENT( EV_USE_ITEM2 ),				// 49
DECLARE_EVENT( EV_USE_ITEM3 ),				// 50
DECLARE_EVENT( EV_USE_ITEM4 ),				// 51
DECLARE_EVENT( EV_USE_ITEM5 ),				// 52
DECLARE_EVENT( EV_USE_ITEM6 ),				// 53
DECLARE_EVENT( EV_USE_ITEM7 ),				// 54
DECLARE_EVENT( EV_USE_ITEM8 ),				// 55
DECLARE_EVENT( EV_USE_ITEM9 ),				// 56
DECLARE_EVENT( EV_USE_ITEM10 ),				// 57
DECLARE_EVENT( EV_USE_ITEM11 ),				// 58
DECLARE_EVENT( EV_USE_ITEM12 ),				// 59
DECLARE_EVENT( EV_USE_ITEM13 ),				// 60
DECLARE_EVENT( EV_USE_ITEM14 ),				// 61
DECLARE_EVENT( EV_USE_ITEM15 ),				// 62

DECLARE_EVENT( EV_ITEM_RESPAWN ),			// 63
DECLARE_EVENT( EV_ITEM_POP ),				// 64
DECLARE_EVENT( EV_PLAYER_TELEPORT_IN ),		// 65
DECLARE_EVENT( EV_PLAYER_TELEPORT_OUT ),	// 66
DECLARE_EVENT( EV_GRENADE_BOUNCE ),			// eventParm will be the soundindex

DECLARE_EVENT( EV_GENERAL_SOUND ),			// 68
DECLARE_EVENT( EV_GLOBAL_SOUND ),			// no attenuation
DECLARE_EVENT( EV_GLOBAL_TEAM_SOUND ),		// 70
DECLARE_EVENT( EV_BULLET_HIT_FLESH ),		// 71
DECLARE_EVENT( EV_BULLET_HIT_WALL ),		// 72
DECLARE_EVENT( EV_MISSILE_HIT ),			// 73
DECLARE_EVENT( EV_MISSILE_MISS ),			// 74
DECLARE_EVENT( EV_MISSILE_MISS_METAL ),		// 75
DECLARE_EVENT( EV_MISSILE_DETONATE ),		// BFP - EV_MISSILE_DETONATE (76), in some moment, ki attack beam/projectile explodes
DECLARE_EVENT( EV_RAILTRAIL ),				// 77
DECLARE_EVENT( EV_SHOTGUN ),				// otherEntity is the shooter
DECLARE_EVENT( EV_UNUSED_INDEX79 ),			// 79

DECLARE_EVENT( EV_PAIN ),					// 80
DECLARE_EVENT( EV_DEATH1 ),					// 81
DECLARE_EVENT( EV_DEATH2 ),					// 82
DECLARE_EVENT( EV_DEATH3 ),					// 83
DECLARE_EVENT( EV_OBITUARY ),				// 84

DECLARE_EVENT( EV_POWERUP_QUAD ),			// 85
DECLARE_EVENT( EV_POWERUP_BATTLESUIT ),		// 86
DECLARE_EVENT( EV_UNUSED_INDEX87 ),			// 87
DECLARE_EVENT( EV_GIB_PLAYER ),				// gib a previously living player

DECLARE_EVENT( EV_UNUSED_INDEX89 ),			// 89
DECLARE_EVENT( EV_UNUSED_INDEX90 ),			// 90
DECLARE_EVENT( EV_SCOREPLUM ),				// score plum

DECLARE_EVENT( EV_TAUNT ),					// 92
DECLARE_EVENT( EV_UNUSED_INDEX93 ),			// 93
DECLARE_EVENT( EV_UNUSED_INDEX94 ),			// 94
DECLARE_EVENT( EV_UNUSED_INDEX95 ),			// 95
DECLARE_EVENT( EV_BLINDING ),				// BFP - EV_BLINDING (reusing 96), when ki attack explodes after some time
DECLARE_EVENT( EV_DEBUG_LINE ),				// 97
DECLARE_EVENT( EV_STOPLOOPINGSOUND ),		// 98

DECLARE_EVENT( EV_BEAM_STRUGGLE )			// BFP - EV_BEAM_STRUGGLE (99), beam struggle

#ifdef EVENT_ENUMS
	, DECLARE_EVENT( EV_MAX )
#endif

#undef DECLARE_EVENT
